// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Windows credential stored in the system keyring.
class WindowsCredential {
  final String username;
  final String password;
  final String instanceName;
  final String projectId;
  final String zone;

  /// ISO 8601 timestamp string (for FFI compatibility)
  final String createdAt;

  /// ISO 8601 timestamp string (optional, for FFI compatibility)
  final String? expiresAt;

  const WindowsCredential({
    required this.username,
    required this.password,
    required this.instanceName,
    required this.projectId,
    required this.zone,
    required this.createdAt,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      password.hashCode ^
      instanceName.hashCode ^
      projectId.hashCode ^
      zone.hashCode ^
      createdAt.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsCredential &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          password == other.password &&
          instanceName == other.instanceName &&
          projectId == other.projectId &&
          zone == other.zone &&
          createdAt == other.createdAt &&
          expiresAt == other.expiresAt;
}
