// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'db_client.dart';
import 'diagnostics.dart';
import 'doctor.dart';
import 'frb_generated.dart';
import 'gcloud.dart';
import 'gcp_rest_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rdp_client.dart';
import 'sftp.dart';
import 'snapshots.dart';
import 'sshfs_mount.dart';
import 'tunnel.dart';
import 'vnc_client.dart';
import 'windows_credentials/storage.dart';

Future<String> testGcpAuthentication() =>
    RustLib.instance.api.crateApiTestGcpAuthentication();

Future<List<GcpProjectClientLib>> listProjectsClientLib() =>
    RustLib.instance.api.crateApiListProjectsClientLib();

Future<String> benchmarkProjectsListing() =>
    RustLib.instance.api.crateApiBenchmarkProjectsListing();

Future<List<GcpInstanceClientLib>> listInstancesClientLib({
  required String projectId,
}) => RustLib.instance.api.crateApiListInstancesClientLib(projectId: projectId);

Future<void> startInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStartInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> stopInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStopInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> resetInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiResetInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> suspendInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiSuspendInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> resumeInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiResumeInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Get a single instance by project, zone, and name.
/// Uses compute.instances.get permission (doesn't require compute.instances.list).
Future<GcpInstanceClientLib> getInstanceClientLib({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetInstanceClientLib(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Get a single instance using gcloud CLI (fallback when REST API fails due to auth).
/// Uses gcloud compute instances describe which uses different authentication.
Future<GcpInstance> getInstanceGcloud({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetInstanceGcloud(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<bool> checkGcloudInstalled() =>
    RustLib.instance.api.crateApiCheckGcloudInstalled();

Future<bool> checkGcloudAuth() =>
    RustLib.instance.api.crateApiCheckGcloudAuth();

/// Get the email of the currently active GCP account
///
/// Uses `gcloud config get-value account` to retrieve the email address
/// of the authenticated user. Returns the full email (e.g., "user@domain.com").
Future<String> getGcloudAccountEmail() =>
    RustLib.instance.api.crateApiGetGcloudAccountEmail();

Future<List<GcpProject>> listProjects() =>
    RustLib.instance.api.crateApiListProjects();

Future<List<GcpInstance>> listInstances({required String projectId}) =>
    RustLib.instance.api.crateApiListInstances(projectId: projectId);

Future<void> gcloudLogin() => RustLib.instance.api.crateApiGcloudLogin();

Future<void> gcloudLogout() => RustLib.instance.api.crateApiGcloudLogout();

/// List all authenticated gcloud accounts
Future<List<GcloudAccount>> listGcloudAccounts() =>
    RustLib.instance.api.crateApiListGcloudAccounts();

/// Switch the active gcloud account
Future<void> switchGcloudAccount({required String email}) =>
    RustLib.instance.api.crateApiSwitchGcloudAccount(email: email);

/// Add a new gcloud account (opens browser)
Future<void> addGcloudAccount() =>
    RustLib.instance.api.crateApiAddGcloudAccount();

/// Remove (revoke) a gcloud account
Future<void> removeGcloudAccount({required String email}) =>
    RustLib.instance.api.crateApiRemoveGcloudAccount(email: email);

/// List projects for a specific account (without changing global config)
Future<List<GcpProject>> listProjectsForAccount({required String email}) =>
    RustLib.instance.api.crateApiListProjectsForAccount(email: email);

Future<void> startInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStartInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> stopInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiStopInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> resetInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiResetInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> suspendInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiSuspendInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> resumeInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiResumeInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Check if a machine type supports the suspend operation
Future<bool> checkSuspendSupport({required String machineType}) =>
    RustLib.instance.api.crateApiCheckSuspendSupport(machineType: machineType);

/// Convert GCP email to OS Login username format
Future<String> emailToOsloginUsername({required String email}) =>
    RustLib.instance.api.crateApiEmailToOsloginUsername(email: email);

Future<void> launchSsh({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiLaunchSsh(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

Future<void> launchSftp({required int port, String? username}) =>
    RustLib.instance.api.crateApiLaunchSftp(port: port, username: username);

Future<String> greet() => RustLib.instance.api.crateApiGreet();

Future<int> startConnection({
  required String projectId,
  required String zone,
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiStartConnection(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<void> stopConnection({
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiStopConnection(
  instanceName: instanceName,
  remotePort: remotePort,
);

Future<bool> checkConnectionHealth({
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiCheckConnectionHealth(
  instanceName: instanceName,
  remotePort: remotePort,
);

/// Measure tunnel latency via TCP connect RTT to local port.
/// Returns latency in milliseconds.
Future<BigInt> measureConnectionLatency({
  required String instanceName,
  required int remotePort,
}) => RustLib.instance.api.crateApiMeasureConnectionLatency(
  instanceName: instanceName,
  remotePort: remotePort,
);

/// Clean up dead tunnel processes. Returns list of cleaned-up tunnel keys.
Future<List<String>> cleanupDeadConnections() =>
    RustLib.instance.api.crateApiCleanupDeadConnections();

/// Get status snapshot of all active tunnels for the global panel.
Future<List<TunnelInfo>> getAllConnectionsStatus() =>
    RustLib.instance.api.crateApiGetAllConnectionsStatus();

Future<RdpLaunchResult> launchRdp({
  required int port,
  required String instanceName,
  required RdpSettings settings,
}) => RustLib.instance.api.crateApiLaunchRdp(
  port: port,
  instanceName: instanceName,
  settings: settings,
);

Future<List<RdpClientType>> getAvailableRdpClients() =>
    RustLib.instance.api.crateApiGetAvailableRdpClients();

/// Clean up old temporary RDP configuration files
///
/// This function should be called at application startup to remove
/// old config files that may contain sensitive data (usernames, domains).
/// Files older than 1 hour are automatically removed.
///
/// # Returns
/// - Number of files cleaned up
Future<int> cleanupRdpConfigFiles() =>
    RustLib.instance.api.crateApiCleanupRdpConfigFiles();

/// Remove a specific RDP config file by instance name
///
/// Call this when closing an RDP connection to immediately clean up
/// the temporary configuration file.
Future<void> removeRdpConfigFile({required String instanceName}) => RustLib
    .instance
    .api
    .crateApiRemoveRdpConfigFile(instanceName: instanceName);

Future<VncLaunchResult> launchVnc({
  required int port,
  required String instanceName,
  required VncSettings settings,
}) => RustLib.instance.api.crateApiLaunchVnc(
  port: port,
  instanceName: instanceName,
  settings: settings,
);

Future<List<VncClientType>> getAvailableVncClients() =>
    RustLib.instance.api.crateApiGetAvailableVncClients();

Future<void> initLoggingSystem() =>
    RustLib.instance.api.crateApiInitLoggingSystem();

Future<String> exportLogsToFile() =>
    RustLib.instance.api.crateApiExportLogsToFile();

Future<String> getLogFilePath() =>
    RustLib.instance.api.crateApiGetLogFilePath();

Future<List<RemoteFileEntry>> sftpListDir({
  required String host,
  required int port,
  required String username,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpListDir(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
);

Future<BigInt> sftpDownload({
  required String host,
  required int port,
  required String username,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpDownload(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
  localPath: localPath,
);

Future<BigInt> sftpUpload({
  required String host,
  required int port,
  required String username,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpUpload(
  host: host,
  port: port,
  username: username,
  localPath: localPath,
  remotePath: remotePath,
);

Future<void> sftpMkdir({
  required String host,
  required int port,
  required String username,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpMkdir(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
);

Future<void> sftpDelete({
  required String host,
  required int port,
  required String username,
  required String remotePath,
  required bool isDirectory,
}) => RustLib.instance.api.crateApiSftpDelete(
  host: host,
  port: port,
  username: username,
  remotePath: remotePath,
  isDirectory: isDirectory,
);

Future<String> getUsername() => RustLib.instance.api.crateApiGetUsername();

/// Get serial port output from a VM instance
///
/// # Arguments
/// * `project_id` - Project ID
/// * `zone` - Zone name (e.g., "us-central1-a")
/// * `instance_name` - Instance name
/// * `port` - Serial port number (1-4, default 1)
/// * `start` - Optional start position for incremental fetch
Future<SerialPortOutput> getSerialOutput({
  required String projectId,
  required String zone,
  required String instanceName,
  required int port,
  PlatformInt64? start,
}) => RustLib.instance.api.crateApiGetSerialOutput(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  port: port,
  start: start,
);

/// Get detailed VM diagnostics including network, disk, and guest agent status
Future<VmDiagnostics> getInstanceDiagnostics({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetInstanceDiagnostics(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Get audit logs for a project, optionally filtered by instance
///
/// # Arguments
/// * `project_id` - Project ID
/// * `instance_name` - Optional instance name to filter by
/// * `max_entries` - Maximum number of entries (default 100)
/// * `hours_ago` - Hours to look back (default 24)
Future<List<AuditLogEntry>> getInstanceAuditLogs({
  required String projectId,
  String? instanceName,
  int? maxEntries,
  int? hoursAgo,
}) => RustLib.instance.api.crateApiGetInstanceAuditLogs(
  projectId: projectId,
  instanceName: instanceName,
  maxEntries: maxEntries,
  hoursAgo: hoursAgo,
);

/// Launch a database client with the specified connection settings
///
/// This function creates an IAP tunnel to the remote database and launches
/// the appropriate SQL client with the connection pre-configured.
///
/// # Arguments
/// * `settings` - Database connection settings including type, host, port, etc.
///
/// # Returns
/// * `DbLaunchResult` - Information about which client was launched
Future<DbLaunchResult> launchDb({required DbConnectionSettings settings}) =>
    RustLib.instance.api.crateApiLaunchDb(settings: settings);

/// Get all database clients available on the system
///
/// Scans for installed database clients (native and Flatpak).
///
/// # Returns
/// * List of available `DbClientType` values
Future<List<DbClientType>> getAvailableDbClients() =>
    RustLib.instance.api.crateApiGetAvailableDbClients();

/// Get available clients for a specific database type
///
/// # Arguments
/// * `db_type` - The database type to get clients for
///
/// # Returns
/// * List of available `DbClientType` values that support the given database type
Future<List<DbClientType>> getAvailableClientsForDbType({
  required DatabaseType dbType,
}) => RustLib.instance.api.crateApiGetAvailableClientsForDbType(dbType: dbType);

/// Get the default port for a database type
///
/// # Arguments
/// * `db_type` - The database type
///
/// # Returns
/// * Default port number (e.g., 3306 for MySQL, 5432 for PostgreSQL)
Future<int> getDefaultDbPort({required DatabaseType dbType}) =>
    RustLib.instance.api.crateApiGetDefaultDbPort(dbType: dbType);

/// Get all supported database types
///
/// # Returns
/// * List of all `DatabaseType` values
Future<List<DatabaseType>> getAllDatabaseTypes() =>
    RustLib.instance.api.crateApiGetAllDatabaseTypes();

/// Clean up old database client configuration files
///
/// Files older than 1 hour are automatically removed.
///
/// # Returns
/// * Number of files cleaned up
Future<int> cleanupDbConfigFiles() =>
    RustLib.instance.api.crateApiCleanupDbConfigFiles();

/// Generate a new Windows password for a VM instance
///
/// This function:
/// 1. Generates an RSA key pair
/// 2. Sends the public key to the VM's metadata
/// 3. Waits for the Windows guest agent to generate the password
/// 4. Decrypts the password
/// 5. Stores the credential securely in the system keyring
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone (e.g., "us-central1-a")
/// * `instance_name` - Name of the Windows VM instance
/// * `username` - Windows username to generate password for
/// * `email` - Email address (for GCP tracking)
///
/// # Returns
/// * `WindowsCredential` containing the username and generated password
Future<WindowsCredential> generateWindowsPassword({
  required String projectId,
  required String zone,
  required String instanceName,
  required String username,
  required String email,
}) => RustLib.instance.api.crateApiGenerateWindowsPassword(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  username: username,
  email: email,
);

/// Reset an existing Windows password for a VM instance
///
/// Same as generate_windows_password but deletes any existing stored credential first.
Future<WindowsCredential> resetWindowsPassword({
  required String projectId,
  required String zone,
  required String instanceName,
  required String username,
  required String email,
}) => RustLib.instance.api.crateApiResetWindowsPassword(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  username: username,
  email: email,
);

/// Get a stored Windows credential for an instance
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone
/// * `instance_name` - Name of the VM instance
///
/// # Returns
/// * `Some(WindowsCredential)` if found, `None` otherwise
Future<WindowsCredential?> getStoredWindowsCredential({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetStoredWindowsCredential(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Get all stored Windows credentials
///
/// # Returns
/// * List of all stored WindowsCredential objects
Future<List<WindowsCredential>> getAllWindowsCredentials() =>
    RustLib.instance.api.crateApiGetAllWindowsCredentials();

/// Delete a stored Windows credential
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone
/// * `instance_name` - Name of the VM instance
Future<void> deleteWindowsCredential({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiDeleteWindowsCredential(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Clear all stored Windows credentials
///
/// # Returns
/// * Number of credentials deleted
Future<int> clearAllWindowsCredentials() =>
    RustLib.instance.api.crateApiClearAllWindowsCredentials();

/// Check if an instance is a Windows VM
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone
/// * `instance_name` - Name of the VM instance
///
/// # Returns
/// * `true` if the instance is a Windows VM, `false` otherwise
Future<bool> isWindowsInstance({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiIsWindowsInstance(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Check SSHFS installation status
///
/// Returns information about sshfs availability, FUSE support,
/// and any issues detected.
Future<SshfsStatus> getSshfsStatus() =>
    RustLib.instance.api.crateApiGetSshfsStatus();

/// Mount a remote directory via SSHFS through an IAP tunnel
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - GCP zone
/// * `instance_name` - VM instance name
/// * `username` - SSH username
/// * `remote_path` - Remote directory to mount (e.g., "/home/user")
/// * `local_mount_point` - Local directory to mount to
/// * `tunnel_port` - Local port of the IAP tunnel
/// * `options` - Mount options
///
/// # Returns
/// * `MountResult` with success status and mount info
Future<MountResult> sshfsMount({
  required String projectId,
  required String zone,
  required String instanceName,
  required String username,
  required String remotePath,
  required String localMountPoint,
  required int tunnelPort,
  required SshfsMountOptions options,
}) => RustLib.instance.api.crateApiSshfsMount(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  username: username,
  remotePath: remotePath,
  localMountPoint: localMountPoint,
  tunnelPort: tunnelPort,
  options: options,
);

/// Unmount an SSHFS mount point
///
/// # Arguments
/// * `mount_point` - Local mount point path to unmount
///
/// # Returns
/// * `UnmountResult` with success status
Future<UnmountResult> sshfsUnmount({required String mountPoint}) =>
    RustLib.instance.api.crateApiSshfsUnmount(mountPoint: mountPoint);

/// Unmount by mount ID
///
/// # Arguments
/// * `mount_id` - The unique mount ID
///
/// # Returns
/// * `UnmountResult` with success status
Future<UnmountResult> sshfsUnmountById({required String mountId}) =>
    RustLib.instance.api.crateApiSshfsUnmountById(mountId: mountId);

/// Get all active SSHFS mounts
///
/// # Returns
/// * List of active `SshfsMount` objects
Future<List<SshfsMount>> getActiveSshfsMounts() =>
    RustLib.instance.api.crateApiGetActiveSshfsMounts();

/// Get active mounts for a specific instance
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `instance_name` - VM instance name
///
/// # Returns
/// * List of `SshfsMount` objects for the instance
Future<List<SshfsMount>> getSshfsMountsForInstance({
  required String projectId,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetSshfsMountsForInstance(
  projectId: projectId,
  instanceName: instanceName,
);

/// Verify if a mount is still active
///
/// # Arguments
/// * `mount_id` - The unique mount ID
///
/// # Returns
/// * `true` if mount is active, `false` otherwise
Future<bool> verifySshfsMountActive({required String mountId}) =>
    RustLib.instance.api.crateApiVerifySshfsMountActive(mountId: mountId);

/// Refresh status of all mounts
///
/// Checks all registered mounts and updates their status,
/// removing any that are no longer mounted.
///
/// # Returns
/// * List of currently active `SshfsMount` objects
Future<List<SshfsMount>> refreshSshfsMountStatus() =>
    RustLib.instance.api.crateApiRefreshSshfsMountStatus();

/// Unmount all active SSHFS mounts
///
/// Used for cleanup when closing the application.
///
/// # Returns
/// * List of `UnmountResult` for each mount
Future<List<UnmountResult>> sshfsUnmountAll() =>
    RustLib.instance.api.crateApiSshfsUnmountAll();

/// Open a mount in the file manager
///
/// # Arguments
/// * `mount_id` - The unique mount ID
/// * `file_manager` - Optional file manager command (uses default if None)
Future<void> openSshfsMountInFileManager({
  required String mountId,
  String? fileManager,
}) => RustLib.instance.api.crateApiOpenSshfsMountInFileManager(
  mountId: mountId,
  fileManager: fileManager,
);

/// Get available file managers
///
/// # Returns
/// * List of `FileManagerInfo` with installed status
Future<List<FileManagerInfo>> getAvailableFileManagers() =>
    RustLib.instance.api.crateApiGetAvailableFileManagers();

/// Get default mount point for a VM
///
/// Creates a path like ~/gcp-mounts/{instance_name}_{remote_path}
///
/// # Arguments
/// * `instance_name` - VM instance name
/// * `remote_path` - Remote directory path
///
/// # Returns
/// * Suggested mount point path
Future<String> getDefaultSshfsMountPoint({
  required String instanceName,
  required String remotePath,
}) => RustLib.instance.api.crateApiGetDefaultSshfsMountPoint(
  instanceName: instanceName,
  remotePath: remotePath,
);

/// Validate a remote path
///
/// Checks for path traversal attempts and normalizes the path.
///
/// # Arguments
/// * `path` - Remote path to validate
///
/// # Returns
/// * Normalized path or error
Future<String> validateSshfsRemotePath({required String path}) =>
    RustLib.instance.api.crateApiValidateSshfsRemotePath(path: path);

/// Validate a local mount point
///
/// Ensures the path is safe and in a user-writable location.
///
/// # Arguments
/// * `path` - Local path to validate
///
/// # Returns
/// * Validated path or error
Future<String> validateSshfsLocalPath({required String path}) =>
    RustLib.instance.api.crateApiValidateSshfsLocalPath(path: path);

/// Run all connectivity doctor checks for a VM instance
///
/// Executes 10 diagnostic checks grouped in 5 categories:
/// Authentication, Project/Permissions, IAP/Network, VM Status, Local Environment.
///
/// # Arguments
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone
/// * `instance_name` - VM instance name
///
/// # Returns
/// * `DoctorReport` with all check results and summary
Future<DoctorReport> runDoctor({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiRunDoctor(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Generate a Markdown report from doctor results
///
/// # Arguments
/// * `report` - The doctor report to format
///
/// # Returns
/// * Markdown string with formatted report
Future<String> generateDoctorReport({required DoctorReport report}) =>
    RustLib.instance.api.crateApiGenerateDoctorReport(report: report);

/// Execute a doctor fix action
///
/// # Arguments
/// * `fix_action_id` - The fix action to execute (e.g., "re_authenticate", "start_vm")
/// * `project_id` - GCP project ID
/// * `zone` - Compute Engine zone
/// * `instance_name` - VM instance name
///
/// # Returns
/// * Success message string
Future<String> executeDoctorFix({
  required String fixActionId,
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiExecuteDoctorFix(
  fixActionId: fixActionId,
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Get the boot disk name for a VM instance by querying gcloud.
Future<String> getBootDiskName({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiGetBootDiskName(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// List all snapshots for the boot disk of a VM instance.
Future<List<GcpSnapshot>> listSnapshots({
  required String projectId,
  required String zone,
  required String instanceName,
}) => RustLib.instance.api.crateApiListSnapshots(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
);

/// Create a snapshot of the boot disk for a VM instance.
Future<void> createSnapshot({
  required String projectId,
  required String zone,
  required String instanceName,
  required String snapshotName,
  required String description,
}) => RustLib.instance.api.crateApiCreateSnapshot(
  projectId: projectId,
  zone: zone,
  instanceName: instanceName,
  snapshotName: snapshotName,
  description: description,
);

/// Delete a snapshot by name.
Future<void> deleteSnapshot({
  required String projectId,
  required String snapshotName,
}) => RustLib.instance.api.crateApiDeleteSnapshot(
  projectId: projectId,
  snapshotName: snapshotName,
);

/// Create a new disk from an existing snapshot (restore operation).
Future<void> createDiskFromSnapshot({
  required String projectId,
  required String zone,
  required String snapshotName,
  required String newDiskName,
}) => RustLib.instance.api.crateApiCreateDiskFromSnapshot(
  projectId: projectId,
  zone: zone,
  snapshotName: snapshotName,
  newDiskName: newDiskName,
);
