// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Supported database types
enum DatabaseType { mySql, postgreSql, sqlServer, redis, mongoDb }

/// Database client types supported by the application
enum DbClientType {
  dBeaver,
  mySqlWorkbench,
  pgAdmin,
  azureDataStudio,
  redisInsight,
  mongoDbCompass,
}

/// Database connection settings
class DbConnectionSettings {
  final DatabaseType databaseType;
  final String host;
  final int port;
  final String? databaseName;
  final String? username;
  final String instanceName;
  final DbClientType? clientType;

  const DbConnectionSettings({
    required this.databaseType,
    required this.host,
    required this.port,
    this.databaseName,
    this.username,
    required this.instanceName,
    this.clientType,
  });

  @override
  int get hashCode =>
      databaseType.hashCode ^
      host.hashCode ^
      port.hashCode ^
      databaseName.hashCode ^
      username.hashCode ^
      instanceName.hashCode ^
      clientType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbConnectionSettings &&
          runtimeType == other.runtimeType &&
          databaseType == other.databaseType &&
          host == other.host &&
          port == other.port &&
          databaseName == other.databaseName &&
          username == other.username &&
          instanceName == other.instanceName &&
          clientType == other.clientType;
}

/// Result of database client launch attempt
class DbLaunchResult {
  final DbClientType clientUsed;
  final bool fallbackOccurred;

  const DbLaunchResult({
    required this.clientUsed,
    required this.fallbackOccurred,
  });

  @override
  int get hashCode => clientUsed.hashCode ^ fallbackOccurred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbLaunchResult &&
          runtimeType == other.runtimeType &&
          clientUsed == other.clientUsed &&
          fallbackOccurred == other.fallbackOccurred;
}
