// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Audit log entry
class AuditLogEntry {
  /// Log entry ID
  final String insertId;

  /// Timestamp
  final String timestamp;

  /// Severity (INFO, WARNING, ERROR)
  final String severity;

  /// Log name
  final String logName;

  /// Resource type (gce_instance, etc.)
  final String resourceType;

  /// Method name (compute.instances.start, etc.)
  final String? methodName;

  /// Principal email (actor)
  final String? principalEmail;

  /// Status code
  final int? statusCode;

  /// Status message
  final String? statusMessage;

  /// Resource name
  final String? resourceName;

  /// Request payload (JSON string, sanitized)
  final String? requestSummary;

  const AuditLogEntry({
    required this.insertId,
    required this.timestamp,
    required this.severity,
    required this.logName,
    required this.resourceType,
    this.methodName,
    this.principalEmail,
    this.statusCode,
    this.statusMessage,
    this.resourceName,
    this.requestSummary,
  });

  @override
  int get hashCode =>
      insertId.hashCode ^
      timestamp.hashCode ^
      severity.hashCode ^
      logName.hashCode ^
      resourceType.hashCode ^
      methodName.hashCode ^
      principalEmail.hashCode ^
      statusCode.hashCode ^
      statusMessage.hashCode ^
      resourceName.hashCode ^
      requestSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditLogEntry &&
          runtimeType == other.runtimeType &&
          insertId == other.insertId &&
          timestamp == other.timestamp &&
          severity == other.severity &&
          logName == other.logName &&
          resourceType == other.resourceType &&
          methodName == other.methodName &&
          principalEmail == other.principalEmail &&
          statusCode == other.statusCode &&
          statusMessage == other.statusMessage &&
          resourceName == other.resourceName &&
          requestSummary == other.requestSummary;
}

/// Disk status information
class DiskStatus {
  /// Disk name/source
  final String name;

  /// Disk type (pd-standard, pd-ssd, etc.)
  final String? diskType;

  /// Disk size in GB
  final int? sizeGb;

  /// Whether this is the boot disk
  final bool isBoot;

  /// Auto-delete flag
  final bool autoDelete;

  /// Mode (READ_WRITE, READ_ONLY)
  final String mode;

  const DiskStatus({
    required this.name,
    this.diskType,
    this.sizeGb,
    required this.isBoot,
    required this.autoDelete,
    required this.mode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      diskType.hashCode ^
      sizeGb.hashCode ^
      isBoot.hashCode ^
      autoDelete.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          diskType == other.diskType &&
          sizeGb == other.sizeGb &&
          isBoot == other.isBoot &&
          autoDelete == other.autoDelete &&
          mode == other.mode;
}

/// Guest OS features and agent status
class GuestAgentStatus {
  /// Whether guest agent is reporting
  final bool isReporting;

  /// Guest OS type (if available)
  final String? osType;

  /// Guest OS version (if available)
  final String? osVersion;

  /// Last heartbeat time
  final String? lastHeartbeat;

  const GuestAgentStatus({
    required this.isReporting,
    this.osType,
    this.osVersion,
    this.lastHeartbeat,
  });

  @override
  int get hashCode =>
      isReporting.hashCode ^
      osType.hashCode ^
      osVersion.hashCode ^
      lastHeartbeat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestAgentStatus &&
          runtimeType == other.runtimeType &&
          isReporting == other.isReporting &&
          osType == other.osType &&
          osVersion == other.osVersion &&
          lastHeartbeat == other.lastHeartbeat;
}

/// Network interface information
class NetworkInterface {
  /// Network name
  final String network;

  /// Subnetwork name
  final String? subnetwork;

  /// Internal IP address
  final String? internalIp;

  /// External IP address (if assigned)
  final String? externalIp;

  /// Network tier (PREMIUM, STANDARD)
  final String? networkTier;

  const NetworkInterface({
    required this.network,
    this.subnetwork,
    this.internalIp,
    this.externalIp,
    this.networkTier,
  });

  @override
  int get hashCode =>
      network.hashCode ^
      subnetwork.hashCode ^
      internalIp.hashCode ^
      externalIp.hashCode ^
      networkTier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInterface &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          subnetwork == other.subnetwork &&
          internalIp == other.internalIp &&
          externalIp == other.externalIp &&
          networkTier == other.networkTier;
}

/// Serial port output from a VM instance
class SerialPortOutput {
  /// The actual serial port content
  final String contents;

  /// Position in the serial port output (for incremental fetching)
  final PlatformInt64 next;

  /// Start position of the returned content
  final PlatformInt64 start;

  /// Instance name
  final String instanceName;

  /// Project ID
  final String projectId;

  /// Zone
  final String zone;

  /// Timestamp when fetched
  final String fetchedAt;

  const SerialPortOutput({
    required this.contents,
    required this.next,
    required this.start,
    required this.instanceName,
    required this.projectId,
    required this.zone,
    required this.fetchedAt,
  });

  @override
  int get hashCode =>
      contents.hashCode ^
      next.hashCode ^
      start.hashCode ^
      instanceName.hashCode ^
      projectId.hashCode ^
      zone.hashCode ^
      fetchedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerialPortOutput &&
          runtimeType == other.runtimeType &&
          contents == other.contents &&
          next == other.next &&
          start == other.start &&
          instanceName == other.instanceName &&
          projectId == other.projectId &&
          zone == other.zone &&
          fetchedAt == other.fetchedAt;
}

/// VM diagnostic information
class VmDiagnostics {
  /// Instance name
  final String instanceName;

  /// Project ID
  final String projectId;

  /// Zone
  final String zone;

  /// Current status (RUNNING, STOPPED, etc.)
  final String status;

  /// Last start timestamp
  final String? lastStartTimestamp;

  /// Last stop timestamp
  final String? lastStopTimestamp;

  /// Guest agent status
  final GuestAgentStatus guestAgentStatus;

  /// Network interfaces
  final List<NetworkInterface> networkInterfaces;

  /// Disk status
  final List<DiskStatus> disks;

  /// Machine type
  final String machineType;

  /// Labels
  final List<(String, String)> labels;

  /// Creation timestamp
  final String? creationTimestamp;

  const VmDiagnostics({
    required this.instanceName,
    required this.projectId,
    required this.zone,
    required this.status,
    this.lastStartTimestamp,
    this.lastStopTimestamp,
    required this.guestAgentStatus,
    required this.networkInterfaces,
    required this.disks,
    required this.machineType,
    required this.labels,
    this.creationTimestamp,
  });

  @override
  int get hashCode =>
      instanceName.hashCode ^
      projectId.hashCode ^
      zone.hashCode ^
      status.hashCode ^
      lastStartTimestamp.hashCode ^
      lastStopTimestamp.hashCode ^
      guestAgentStatus.hashCode ^
      networkInterfaces.hashCode ^
      disks.hashCode ^
      machineType.hashCode ^
      labels.hashCode ^
      creationTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VmDiagnostics &&
          runtimeType == other.runtimeType &&
          instanceName == other.instanceName &&
          projectId == other.projectId &&
          zone == other.zone &&
          status == other.status &&
          lastStartTimestamp == other.lastStartTimestamp &&
          lastStopTimestamp == other.lastStopTimestamp &&
          guestAgentStatus == other.guestAgentStatus &&
          networkInterfaces == other.networkInterfaces &&
          disks == other.disks &&
          machineType == other.machineType &&
          labels == other.labels &&
          creationTimestamp == other.creationTimestamp;
}
