// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum DoctorCheckCategory {
  authentication,
  projectPermissions,
  iapNetwork,
  vmStatus,
  localEnvironment,
}

class DoctorCheckResult {
  final String checkId;
  final String name;
  final DoctorCheckCategory category;
  final DoctorCheckStatus status;
  final String message;
  final String? details;
  final String? suggestion;
  final String? fixCommand;
  final String? fixActionId;
  final BigInt durationMs;

  const DoctorCheckResult({
    required this.checkId,
    required this.name,
    required this.category,
    required this.status,
    required this.message,
    this.details,
    this.suggestion,
    this.fixCommand,
    this.fixActionId,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      checkId.hashCode ^
      name.hashCode ^
      category.hashCode ^
      status.hashCode ^
      message.hashCode ^
      details.hashCode ^
      suggestion.hashCode ^
      fixCommand.hashCode ^
      fixActionId.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DoctorCheckResult &&
          runtimeType == other.runtimeType &&
          checkId == other.checkId &&
          name == other.name &&
          category == other.category &&
          status == other.status &&
          message == other.message &&
          details == other.details &&
          suggestion == other.suggestion &&
          fixCommand == other.fixCommand &&
          fixActionId == other.fixActionId &&
          durationMs == other.durationMs;
}

enum DoctorCheckStatus { pass, warning, fail, skipped }

class DoctorReport {
  final List<DoctorCheckResult> checks;
  final String projectId;
  final String zone;
  final String instanceName;
  final String generatedAt;
  final String? gcloudVersion;
  final String? gcloudAccount;
  final BigInt totalDurationMs;
  final int passCount;
  final int warningCount;
  final int failCount;
  final int skippedCount;

  const DoctorReport({
    required this.checks,
    required this.projectId,
    required this.zone,
    required this.instanceName,
    required this.generatedAt,
    this.gcloudVersion,
    this.gcloudAccount,
    required this.totalDurationMs,
    required this.passCount,
    required this.warningCount,
    required this.failCount,
    required this.skippedCount,
  });

  @override
  int get hashCode =>
      checks.hashCode ^
      projectId.hashCode ^
      zone.hashCode ^
      instanceName.hashCode ^
      generatedAt.hashCode ^
      gcloudVersion.hashCode ^
      gcloudAccount.hashCode ^
      totalDurationMs.hashCode ^
      passCount.hashCode ^
      warningCount.hashCode ^
      failCount.hashCode ^
      skippedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DoctorReport &&
          runtimeType == other.runtimeType &&
          checks == other.checks &&
          projectId == other.projectId &&
          zone == other.zone &&
          instanceName == other.instanceName &&
          generatedAt == other.generatedAt &&
          gcloudVersion == other.gcloudVersion &&
          gcloudAccount == other.gcloudAccount &&
          totalDurationMs == other.totalDurationMs &&
          passCount == other.passCount &&
          warningCount == other.warningCount &&
          failCount == other.failCount &&
          skippedCount == other.skippedCount;
}
