// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'db_client.dart';
import 'diagnostics.dart';
import 'doctor.dart';
import 'frb_generated.dart';
import 'gcloud.dart';
import 'gcp_rest_client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'rdp_client.dart';
import 'sftp.dart';
import 'snapshots.dart';
import 'sshfs_mount.dart';
import 'tunnel.dart';
import 'vnc_client.dart';
import 'windows_credentials/storage.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SftpProgress> dco_decode_StreamSink_sftp_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuditLogEntry dco_decode_audit_log_entry(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DbClientType dco_decode_box_autoadd_db_client_type(dynamic raw);

  @protected
  DbConnectionSettings dco_decode_box_autoadd_db_connection_settings(
    dynamic raw,
  );

  @protected
  DoctorReport dco_decode_box_autoadd_doctor_report(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  RdpSettings dco_decode_box_autoadd_rdp_settings(dynamic raw);

  @protected
  SshfsMount dco_decode_box_autoadd_sshfs_mount(dynamic raw);

  @protected
  SshfsMountOptions dco_decode_box_autoadd_sshfs_mount_options(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  VncSettings dco_decode_box_autoadd_vnc_settings(dynamic raw);

  @protected
  WindowsCredential dco_decode_box_autoadd_windows_credential(dynamic raw);

  @protected
  DatabaseType dco_decode_database_type(dynamic raw);

  @protected
  DbClientType dco_decode_db_client_type(dynamic raw);

  @protected
  DbConnectionSettings dco_decode_db_connection_settings(dynamic raw);

  @protected
  DbLaunchResult dco_decode_db_launch_result(dynamic raw);

  @protected
  DiskStatus dco_decode_disk_status(dynamic raw);

  @protected
  DoctorCheckCategory dco_decode_doctor_check_category(dynamic raw);

  @protected
  DoctorCheckResult dco_decode_doctor_check_result(dynamic raw);

  @protected
  DoctorCheckStatus dco_decode_doctor_check_status(dynamic raw);

  @protected
  DoctorReport dco_decode_doctor_report(dynamic raw);

  @protected
  FileManagerInfo dco_decode_file_manager_info(dynamic raw);

  @protected
  GcloudAccount dco_decode_gcloud_account(dynamic raw);

  @protected
  GcpInstance dco_decode_gcp_instance(dynamic raw);

  @protected
  GcpInstanceClientLib dco_decode_gcp_instance_client_lib(dynamic raw);

  @protected
  GcpProject dco_decode_gcp_project(dynamic raw);

  @protected
  GcpProjectClientLib dco_decode_gcp_project_client_lib(dynamic raw);

  @protected
  GcpSnapshot dco_decode_gcp_snapshot(dynamic raw);

  @protected
  GuestAgentStatus dco_decode_guest_agent_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuditLogEntry> dco_decode_list_audit_log_entry(dynamic raw);

  @protected
  List<DatabaseType> dco_decode_list_database_type(dynamic raw);

  @protected
  List<DbClientType> dco_decode_list_db_client_type(dynamic raw);

  @protected
  List<DiskStatus> dco_decode_list_disk_status(dynamic raw);

  @protected
  List<DoctorCheckResult> dco_decode_list_doctor_check_result(dynamic raw);

  @protected
  List<FileManagerInfo> dco_decode_list_file_manager_info(dynamic raw);

  @protected
  List<GcloudAccount> dco_decode_list_gcloud_account(dynamic raw);

  @protected
  List<GcpInstance> dco_decode_list_gcp_instance(dynamic raw);

  @protected
  List<GcpInstanceClientLib> dco_decode_list_gcp_instance_client_lib(
    dynamic raw,
  );

  @protected
  List<GcpProject> dco_decode_list_gcp_project(dynamic raw);

  @protected
  List<GcpProjectClientLib> dco_decode_list_gcp_project_client_lib(dynamic raw);

  @protected
  List<GcpSnapshot> dco_decode_list_gcp_snapshot(dynamic raw);

  @protected
  List<NetworkInterface> dco_decode_list_network_interface(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RdpClientType> dco_decode_list_rdp_client_type(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RemoteFileEntry> dco_decode_list_remote_file_entry(dynamic raw);

  @protected
  List<SshfsMount> dco_decode_list_sshfs_mount(dynamic raw);

  @protected
  List<TunnelInfo> dco_decode_list_tunnel_info(dynamic raw);

  @protected
  List<UnmountResult> dco_decode_list_unmount_result(dynamic raw);

  @protected
  List<VncClientType> dco_decode_list_vnc_client_type(dynamic raw);

  @protected
  List<WindowsCredential> dco_decode_list_windows_credential(dynamic raw);

  @protected
  MountResult dco_decode_mount_result(dynamic raw);

  @protected
  NetworkInterface dco_decode_network_interface(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DbClientType? dco_decode_opt_box_autoadd_db_client_type(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SshfsMount? dco_decode_opt_box_autoadd_sshfs_mount(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  WindowsCredential? dco_decode_opt_box_autoadd_windows_credential(dynamic raw);

  @protected
  RdpClientType dco_decode_rdp_client_type(dynamic raw);

  @protected
  RdpLaunchResult dco_decode_rdp_launch_result(dynamic raw);

  @protected
  RdpSettings dco_decode_rdp_settings(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RemoteFileEntry dco_decode_remote_file_entry(dynamic raw);

  @protected
  SerialPortOutput dco_decode_serial_port_output(dynamic raw);

  @protected
  SftpProgress dco_decode_sftp_progress(dynamic raw);

  @protected
  SshfsMount dco_decode_sshfs_mount(dynamic raw);

  @protected
  SshfsMountOptions dco_decode_sshfs_mount_options(dynamic raw);

  @protected
  SshfsStatus dco_decode_sshfs_status(dynamic raw);

  @protected
  TunnelFailure dco_decode_tunnel_failure(dynamic raw);

  @protected
  TunnelInfo dco_decode_tunnel_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnmountResult dco_decode_unmount_result(dynamic raw);

  @protected
  VmDiagnostics dco_decode_vm_diagnostics(dynamic raw);

  @protected
  VncClientType dco_decode_vnc_client_type(dynamic raw);

  @protected
  VncLaunchResult dco_decode_vnc_launch_result(dynamic raw);

  @protected
  VncQuality dco_decode_vnc_quality(dynamic raw);

  @protected
  VncSettings dco_decode_vnc_settings(dynamic raw);

  @protected
  WindowsCredential dco_decode_windows_credential(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SftpProgress> sse_decode_StreamSink_sftp_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuditLogEntry sse_decode_audit_log_entry(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DbClientType sse_decode_box_autoadd_db_client_type(
    SseDeserializer deserializer,
  );

  @protected
  DbConnectionSettings sse_decode_box_autoadd_db_connection_settings(
    SseDeserializer deserializer,
  );

  @protected
  DoctorReport sse_decode_box_autoadd_doctor_report(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RdpSettings sse_decode_box_autoadd_rdp_settings(SseDeserializer deserializer);

  @protected
  SshfsMount sse_decode_box_autoadd_sshfs_mount(SseDeserializer deserializer);

  @protected
  SshfsMountOptions sse_decode_box_autoadd_sshfs_mount_options(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  VncSettings sse_decode_box_autoadd_vnc_settings(SseDeserializer deserializer);

  @protected
  WindowsCredential sse_decode_box_autoadd_windows_credential(
    SseDeserializer deserializer,
  );

  @protected
  DatabaseType sse_decode_database_type(SseDeserializer deserializer);

  @protected
  DbClientType sse_decode_db_client_type(SseDeserializer deserializer);

  @protected
  DbConnectionSettings sse_decode_db_connection_settings(
    SseDeserializer deserializer,
  );

  @protected
  DbLaunchResult sse_decode_db_launch_result(SseDeserializer deserializer);

  @protected
  DiskStatus sse_decode_disk_status(SseDeserializer deserializer);

  @protected
  DoctorCheckCategory sse_decode_doctor_check_category(
    SseDeserializer deserializer,
  );

  @protected
  DoctorCheckResult sse_decode_doctor_check_result(
    SseDeserializer deserializer,
  );

  @protected
  DoctorCheckStatus sse_decode_doctor_check_status(
    SseDeserializer deserializer,
  );

  @protected
  DoctorReport sse_decode_doctor_report(SseDeserializer deserializer);

  @protected
  FileManagerInfo sse_decode_file_manager_info(SseDeserializer deserializer);

  @protected
  GcloudAccount sse_decode_gcloud_account(SseDeserializer deserializer);

  @protected
  GcpInstance sse_decode_gcp_instance(SseDeserializer deserializer);

  @protected
  GcpInstanceClientLib sse_decode_gcp_instance_client_lib(
    SseDeserializer deserializer,
  );

  @protected
  GcpProject sse_decode_gcp_project(SseDeserializer deserializer);

  @protected
  GcpProjectClientLib sse_decode_gcp_project_client_lib(
    SseDeserializer deserializer,
  );

  @protected
  GcpSnapshot sse_decode_gcp_snapshot(SseDeserializer deserializer);

  @protected
  GuestAgentStatus sse_decode_guest_agent_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuditLogEntry> sse_decode_list_audit_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<DatabaseType> sse_decode_list_database_type(
    SseDeserializer deserializer,
  );

  @protected
  List<DbClientType> sse_decode_list_db_client_type(
    SseDeserializer deserializer,
  );

  @protected
  List<DiskStatus> sse_decode_list_disk_status(SseDeserializer deserializer);

  @protected
  List<DoctorCheckResult> sse_decode_list_doctor_check_result(
    SseDeserializer deserializer,
  );

  @protected
  List<FileManagerInfo> sse_decode_list_file_manager_info(
    SseDeserializer deserializer,
  );

  @protected
  List<GcloudAccount> sse_decode_list_gcloud_account(
    SseDeserializer deserializer,
  );

  @protected
  List<GcpInstance> sse_decode_list_gcp_instance(SseDeserializer deserializer);

  @protected
  List<GcpInstanceClientLib> sse_decode_list_gcp_instance_client_lib(
    SseDeserializer deserializer,
  );

  @protected
  List<GcpProject> sse_decode_list_gcp_project(SseDeserializer deserializer);

  @protected
  List<GcpProjectClientLib> sse_decode_list_gcp_project_client_lib(
    SseDeserializer deserializer,
  );

  @protected
  List<GcpSnapshot> sse_decode_list_gcp_snapshot(SseDeserializer deserializer);

  @protected
  List<NetworkInterface> sse_decode_list_network_interface(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RdpClientType> sse_decode_list_rdp_client_type(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<RemoteFileEntry> sse_decode_list_remote_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<SshfsMount> sse_decode_list_sshfs_mount(SseDeserializer deserializer);

  @protected
  List<TunnelInfo> sse_decode_list_tunnel_info(SseDeserializer deserializer);

  @protected
  List<UnmountResult> sse_decode_list_unmount_result(
    SseDeserializer deserializer,
  );

  @protected
  List<VncClientType> sse_decode_list_vnc_client_type(
    SseDeserializer deserializer,
  );

  @protected
  List<WindowsCredential> sse_decode_list_windows_credential(
    SseDeserializer deserializer,
  );

  @protected
  MountResult sse_decode_mount_result(SseDeserializer deserializer);

  @protected
  NetworkInterface sse_decode_network_interface(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DbClientType? sse_decode_opt_box_autoadd_db_client_type(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SshfsMount? sse_decode_opt_box_autoadd_sshfs_mount(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  WindowsCredential? sse_decode_opt_box_autoadd_windows_credential(
    SseDeserializer deserializer,
  );

  @protected
  RdpClientType sse_decode_rdp_client_type(SseDeserializer deserializer);

  @protected
  RdpLaunchResult sse_decode_rdp_launch_result(SseDeserializer deserializer);

  @protected
  RdpSettings sse_decode_rdp_settings(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RemoteFileEntry sse_decode_remote_file_entry(SseDeserializer deserializer);

  @protected
  SerialPortOutput sse_decode_serial_port_output(SseDeserializer deserializer);

  @protected
  SftpProgress sse_decode_sftp_progress(SseDeserializer deserializer);

  @protected
  SshfsMount sse_decode_sshfs_mount(SseDeserializer deserializer);

  @protected
  SshfsMountOptions sse_decode_sshfs_mount_options(
    SseDeserializer deserializer,
  );

  @protected
  SshfsStatus sse_decode_sshfs_status(SseDeserializer deserializer);

  @protected
  TunnelFailure sse_decode_tunnel_failure(SseDeserializer deserializer);

  @protected
  TunnelInfo sse_decode_tunnel_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnmountResult sse_decode_unmount_result(SseDeserializer deserializer);

  @protected
  VmDiagnostics sse_decode_vm_diagnostics(SseDeserializer deserializer);

  @protected
  VncClientType sse_decode_vnc_client_type(SseDeserializer deserializer);

  @protected
  VncLaunchResult sse_decode_vnc_launch_result(SseDeserializer deserializer);

  @protected
  VncQuality sse_decode_vnc_quality(SseDeserializer deserializer);

  @protected
  VncSettings sse_decode_vnc_settings(SseDeserializer deserializer);

  @protected
  WindowsCredential sse_decode_windows_credential(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sftp_progress_Sse(
    RustStreamSink<SftpProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audit_log_entry(AuditLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_db_client_type(
    DbClientType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_db_connection_settings(
    DbConnectionSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_doctor_report(
    DoctorReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rdp_settings(
    RdpSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sshfs_mount(
    SshfsMount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sshfs_mount_options(
    SshfsMountOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vnc_settings(
    VncSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_windows_credential(
    WindowsCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_database_type(DatabaseType self, SseSerializer serializer);

  @protected
  void sse_encode_db_client_type(DbClientType self, SseSerializer serializer);

  @protected
  void sse_encode_db_connection_settings(
    DbConnectionSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_launch_result(
    DbLaunchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_disk_status(DiskStatus self, SseSerializer serializer);

  @protected
  void sse_encode_doctor_check_category(
    DoctorCheckCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_doctor_check_result(
    DoctorCheckResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_doctor_check_status(
    DoctorCheckStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_doctor_report(DoctorReport self, SseSerializer serializer);

  @protected
  void sse_encode_file_manager_info(
    FileManagerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gcloud_account(GcloudAccount self, SseSerializer serializer);

  @protected
  void sse_encode_gcp_instance(GcpInstance self, SseSerializer serializer);

  @protected
  void sse_encode_gcp_instance_client_lib(
    GcpInstanceClientLib self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gcp_project(GcpProject self, SseSerializer serializer);

  @protected
  void sse_encode_gcp_project_client_lib(
    GcpProjectClientLib self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gcp_snapshot(GcpSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_guest_agent_status(
    GuestAgentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_log_entry(
    List<AuditLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_database_type(
    List<DatabaseType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_db_client_type(
    List<DbClientType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_disk_status(
    List<DiskStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_doctor_check_result(
    List<DoctorCheckResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_info(
    List<FileManagerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcloud_account(
    List<GcloudAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcp_instance(
    List<GcpInstance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcp_instance_client_lib(
    List<GcpInstanceClientLib> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcp_project(
    List<GcpProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcp_project_client_lib(
    List<GcpProjectClientLib> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gcp_snapshot(
    List<GcpSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network_interface(
    List<NetworkInterface> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rdp_client_type(
    List<RdpClientType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_remote_file_entry(
    List<RemoteFileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sshfs_mount(
    List<SshfsMount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tunnel_info(
    List<TunnelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unmount_result(
    List<UnmountResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vnc_client_type(
    List<VncClientType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_windows_credential(
    List<WindowsCredential> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mount_result(MountResult self, SseSerializer serializer);

  @protected
  void sse_encode_network_interface(
    NetworkInterface self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_db_client_type(
    DbClientType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sshfs_mount(
    SshfsMount? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_windows_credential(
    WindowsCredential? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rdp_client_type(RdpClientType self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_launch_result(
    RdpLaunchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rdp_settings(RdpSettings self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_file_entry(
    RemoteFileEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_serial_port_output(
    SerialPortOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sftp_progress(SftpProgress self, SseSerializer serializer);

  @protected
  void sse_encode_sshfs_mount(SshfsMount self, SseSerializer serializer);

  @protected
  void sse_encode_sshfs_mount_options(
    SshfsMountOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sshfs_status(SshfsStatus self, SseSerializer serializer);

  @protected
  void sse_encode_tunnel_failure(TunnelFailure self, SseSerializer serializer);

  @protected
  void sse_encode_tunnel_info(TunnelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unmount_result(UnmountResult self, SseSerializer serializer);

  @protected
  void sse_encode_vm_diagnostics(VmDiagnostics self, SseSerializer serializer);

  @protected
  void sse_encode_vnc_client_type(VncClientType self, SseSerializer serializer);

  @protected
  void sse_encode_vnc_launch_result(
    VncLaunchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vnc_quality(VncQuality self, SseSerializer serializer);

  @protected
  void sse_encode_vnc_settings(VncSettings self, SseSerializer serializer);

  @protected
  void sse_encode_windows_credential(
    WindowsCredential self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
