// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GcloudAccount {
  final String account;
  final String status;

  const GcloudAccount({required this.account, required this.status});

  @override
  int get hashCode => account.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcloudAccount &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          status == other.status;
}

class GcpInstance {
  final String name;
  final String status;
  final String zone;
  final String machineType;
  final int? cpuCount;
  final int? memoryMb;
  final int? diskGb;
  final List<(String, String)> labels;
  final bool osLoginEnabled;
  final bool isWindows;

  const GcpInstance({
    required this.name,
    required this.status,
    required this.zone,
    required this.machineType,
    this.cpuCount,
    this.memoryMb,
    this.diskGb,
    required this.labels,
    required this.osLoginEnabled,
    required this.isWindows,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      status.hashCode ^
      zone.hashCode ^
      machineType.hashCode ^
      cpuCount.hashCode ^
      memoryMb.hashCode ^
      diskGb.hashCode ^
      labels.hashCode ^
      osLoginEnabled.hashCode ^
      isWindows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpInstance &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          zone == other.zone &&
          machineType == other.machineType &&
          cpuCount == other.cpuCount &&
          memoryMb == other.memoryMb &&
          diskGb == other.diskGb &&
          labels == other.labels &&
          osLoginEnabled == other.osLoginEnabled &&
          isWindows == other.isWindows;
}

class GcpProject {
  final String projectId;
  final String? name;

  const GcpProject({required this.projectId, this.name});

  @override
  int get hashCode => projectId.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpProject &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          name == other.name;
}
