// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Google Cloud Compute Instance (Client Library version)
class GcpInstanceClientLib {
  final String name;
  final String status;
  final String zone;
  final String machineType;
  final int? cpuCount;
  final int? memoryMb;
  final int? diskGb;
  final List<(String, String)> labels;
  final bool osLoginEnabled;
  final bool isWindows;

  const GcpInstanceClientLib({
    required this.name,
    required this.status,
    required this.zone,
    required this.machineType,
    this.cpuCount,
    this.memoryMb,
    this.diskGb,
    required this.labels,
    required this.osLoginEnabled,
    required this.isWindows,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      status.hashCode ^
      zone.hashCode ^
      machineType.hashCode ^
      cpuCount.hashCode ^
      memoryMb.hashCode ^
      diskGb.hashCode ^
      labels.hashCode ^
      osLoginEnabled.hashCode ^
      isWindows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpInstanceClientLib &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          zone == other.zone &&
          machineType == other.machineType &&
          cpuCount == other.cpuCount &&
          memoryMb == other.memoryMb &&
          diskGb == other.diskGb &&
          labels == other.labels &&
          osLoginEnabled == other.osLoginEnabled &&
          isWindows == other.isWindows;
}

/// Google Cloud Project (Client Library version)
/// This struct is used by the Client Libraries implementation
class GcpProjectClientLib {
  final String projectId;
  final String? name;
  final String projectNumber;
  final String state;

  const GcpProjectClientLib({
    required this.projectId,
    this.name,
    required this.projectNumber,
    required this.state,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      name.hashCode ^
      projectNumber.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpProjectClientLib &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          name == other.name &&
          projectNumber == other.projectNumber &&
          state == other.state;
}
