// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RdpSettings {
  final String? username;
  final String? password;
  final String? domain;
  final int? width;
  final int? height;
  final bool fullscreen;

  /// Whether to ignore certificate validation errors
  /// Default: false (validate certificates for security)
  /// Set to true only if connecting to trusted hosts with self-signed certs
  final bool ignoreCertificate;

  const RdpSettings({
    this.username,
    this.password,
    this.domain,
    this.width,
    this.height,
    required this.fullscreen,
    required this.ignoreCertificate,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fullscreen.hashCode ^
      ignoreCertificate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSettings &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          width == other.width &&
          height == other.height &&
          fullscreen == other.fullscreen &&
          ignoreCertificate == other.ignoreCertificate;
}
