// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Represents a GCP disk snapshot.
class GcpSnapshot {
  final String name;
  final String status;
  final String creationTimestamp;
  final String sourceDisk;
  final BigInt diskSizeGb;
  final BigInt storageBytes;
  final String description;

  const GcpSnapshot({
    required this.name,
    required this.status,
    required this.creationTimestamp,
    required this.sourceDisk,
    required this.diskSizeGb,
    required this.storageBytes,
    required this.description,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      status.hashCode ^
      creationTimestamp.hashCode ^
      sourceDisk.hashCode ^
      diskSizeGb.hashCode ^
      storageBytes.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GcpSnapshot &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          creationTimestamp == other.creationTimestamp &&
          sourceDisk == other.sourceDisk &&
          diskSizeGb == other.diskSizeGb &&
          storageBytes == other.storageBytes &&
          description == other.description;
}
