// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Information about available file managers
class FileManagerInfo {
  final String name;
  final String command;
  final bool isInstalled;

  const FileManagerInfo({
    required this.name,
    required this.command,
    required this.isInstalled,
  });

  @override
  int get hashCode => name.hashCode ^ command.hashCode ^ isInstalled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          command == other.command &&
          isInstalled == other.isInstalled;
}

/// Result of a mount operation
class MountResult {
  /// Whether the operation succeeded
  final bool success;

  /// The mount information (if successful)
  final SshfsMount? mount;

  /// Error message (if failed)
  final String? error;

  /// Mount point path
  final String mountPoint;

  const MountResult({
    required this.success,
    this.mount,
    this.error,
    required this.mountPoint,
  });

  @override
  int get hashCode =>
      success.hashCode ^ mount.hashCode ^ error.hashCode ^ mountPoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MountResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          mount == other.mount &&
          error == other.error &&
          mountPoint == other.mountPoint;
}

/// Represents an active SSHFS mount
class SshfsMount {
  /// Unique identifier for this mount
  final String id;

  /// GCP project ID
  final String projectId;

  /// GCP zone
  final String zone;

  /// VM instance name
  final String instanceName;

  /// Remote directory path (e.g., /home/user)
  final String remotePath;

  /// Local mount point (e.g., /home/localuser/mounts/vm-name)
  final String localMountPoint;

  /// SSH username for the connection
  final String username;

  /// Local tunnel port being used
  final int tunnelPort;

  /// Mount options used
  final SshfsMountOptions options;

  /// Whether the mount is currently active
  final bool isActive;

  /// Timestamp when mount was created (Unix timestamp)
  final PlatformInt64 createdAt;

  const SshfsMount({
    required this.id,
    required this.projectId,
    required this.zone,
    required this.instanceName,
    required this.remotePath,
    required this.localMountPoint,
    required this.username,
    required this.tunnelPort,
    required this.options,
    required this.isActive,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      projectId.hashCode ^
      zone.hashCode ^
      instanceName.hashCode ^
      remotePath.hashCode ^
      localMountPoint.hashCode ^
      username.hashCode ^
      tunnelPort.hashCode ^
      options.hashCode ^
      isActive.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshfsMount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          projectId == other.projectId &&
          zone == other.zone &&
          instanceName == other.instanceName &&
          remotePath == other.remotePath &&
          localMountPoint == other.localMountPoint &&
          username == other.username &&
          tunnelPort == other.tunnelPort &&
          options == other.options &&
          isActive == other.isActive &&
          createdAt == other.createdAt;
}

/// Mount options for SSHFS
class SshfsMountOptions {
  /// Read-only mount
  final bool readOnly;

  /// Enable caching (improves performance but may show stale data)
  final bool cache;

  /// Enable compression (useful for slow connections)
  final bool compression;

  /// Auto-reconnect on connection loss
  final bool reconnect;

  /// Server alive interval in seconds (for reconnect)
  final int serverAliveInterval;

  /// Allow other users to access the mount (requires user_allow_other in /etc/fuse.conf)
  final bool allowOther;

  /// Follow symlinks on the server
  final bool followSymlinks;

  /// Custom SSH port (default: 22)
  final int? sshPort;

  /// SSH identity file path
  final String? identityFile;

  const SshfsMountOptions({
    required this.readOnly,
    required this.cache,
    required this.compression,
    required this.reconnect,
    required this.serverAliveInterval,
    required this.allowOther,
    required this.followSymlinks,
    this.sshPort,
    this.identityFile,
  });

  @override
  int get hashCode =>
      readOnly.hashCode ^
      cache.hashCode ^
      compression.hashCode ^
      reconnect.hashCode ^
      serverAliveInterval.hashCode ^
      allowOther.hashCode ^
      followSymlinks.hashCode ^
      sshPort.hashCode ^
      identityFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshfsMountOptions &&
          runtimeType == other.runtimeType &&
          readOnly == other.readOnly &&
          cache == other.cache &&
          compression == other.compression &&
          reconnect == other.reconnect &&
          serverAliveInterval == other.serverAliveInterval &&
          allowOther == other.allowOther &&
          followSymlinks == other.followSymlinks &&
          sshPort == other.sshPort &&
          identityFile == other.identityFile;
}

/// SSHFS installation status
class SshfsStatus {
  /// Whether sshfs is installed
  final bool installed;

  /// Whether FUSE is available
  final bool fuseAvailable;

  /// sshfs version string (if installed)
  final String? version;

  /// Path to sshfs binary
  final String? binaryPath;

  /// Any issues detected
  final List<String> issues;

  const SshfsStatus({
    required this.installed,
    required this.fuseAvailable,
    this.version,
    this.binaryPath,
    required this.issues,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      fuseAvailable.hashCode ^
      version.hashCode ^
      binaryPath.hashCode ^
      issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshfsStatus &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          fuseAvailable == other.fuseAvailable &&
          version == other.version &&
          binaryPath == other.binaryPath &&
          issues == other.issues;
}

/// Result of an unmount operation
class UnmountResult {
  /// Whether the operation succeeded
  final bool success;

  /// Error message (if failed)
  final String? error;

  /// Mount point that was unmounted
  final String mountPoint;

  const UnmountResult({
    required this.success,
    this.error,
    required this.mountPoint,
  });

  @override
  int get hashCode => success.hashCode ^ error.hashCode ^ mountPoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnmountResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error &&
          mountPoint == other.mountPoint;
}
