// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Information about a tunnel's current state, exposed to Dart via bridge
class TunnelInfo {
  final String key;
  final int localPort;
  final bool isHealthy;

  const TunnelInfo({
    required this.key,
    required this.localPort,
    required this.isHealthy,
  });

  @override
  int get hashCode => key.hashCode ^ localPort.hashCode ^ isHealthy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunnelInfo &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          localPort == other.localPort &&
          isHealthy == other.isHealthy;
}
