// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// VNC Client Type - Auto-synced to Dart via Flutter Rust Bridge
enum VncClientType { remmina, tigerVnc, krdc, vinagre }

/// Result of VNC launch attempt
class VncLaunchResult {
  final VncClientType clientUsed;
  final bool fallbackOccurred;

  const VncLaunchResult({
    required this.clientUsed,
    required this.fallbackOccurred,
  });

  @override
  int get hashCode => clientUsed.hashCode ^ fallbackOccurred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VncLaunchResult &&
          runtimeType == other.runtimeType &&
          clientUsed == other.clientUsed &&
          fallbackOccurred == other.fallbackOccurred;
}

/// VNC Quality Settings
enum VncQuality { high, medium, low, auto }

/// VNC connection settings
class VncSettings {
  final String? password;
  final int? width;
  final int? height;
  final bool fullscreen;

  /// View-only mode (read-only access, no keyboard/mouse input)
  final bool viewOnly;

  /// Quality/compression level
  final VncQuality quality;

  /// User's preferred VNC client
  final VncClientType clientType;

  const VncSettings({
    this.password,
    this.width,
    this.height,
    required this.fullscreen,
    required this.viewOnly,
    required this.quality,
    required this.clientType,
  });

  @override
  int get hashCode =>
      password.hashCode ^
      width.hashCode ^
      height.hashCode ^
      fullscreen.hashCode ^
      viewOnly.hashCode ^
      quality.hashCode ^
      clientType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VncSettings &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          width == other.width &&
          height == other.height &&
          fullscreen == other.fullscreen &&
          viewOnly == other.viewOnly &&
          quality == other.quality &&
          clientType == other.clientType;
}
